app = "matchmaker-staging-bot"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[processes]
  app = "python -m bot.main"

[vm]
  size = "shared-cpu-1x"
  memory = "512mb"

[env]
  PYTHONUNBUFFERED = "1"
