name: Deploy Staging to Fly.io
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master

      # Build with the runner's Docker and deploy (avoids remote builder/Depot)
      - name: Deploy (local build on runner)
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy -a matchmaker-staging-bot --local-only
