name: Deploy Staging
on:
  push:
    branches: [ develop ]
  workflow_dispatch: {}

concurrency:
  group: staging-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://matchmaker-staging-bot.fly.dev/health
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      # ensure app secrets exist (safe to re-run)
      - name: Set Fly app secrets
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          DISCORD_TOKEN: ${{ secrets.STAGING_DISCORD_TOKEN }}
          INVITE_URL: ${{ secrets.STAGING_PUBLIC_INVITE_URL }}
        run: |
          flyctl secrets set \
            DISCORD_TOKEN="$DISCORD_TOKEN" \
            ENVIRONMENT=staging \
            PUBLIC_INVITE_URL="${INVITE_URL:-}" \
            -a matchmaker-staging-bot

      # build with runner's Docker (no Depot) and deploy using staging toml
      - name: Deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl deploy --local-only -c fly.staging.toml
