name: Deploy Production
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

concurrency:
  group: prod-deploy
  cancel-in-progress: true


jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Set Fly secrets (production)
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          DISCORD_TOKEN: ${{ secrets.PROD_DISCORD_TOKEN }}
          DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
          PROD_DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
          INVITE_URL: ${{ secrets.PROD_PUBLIC_INVITE_URL }}
        run: |
          # Set all secrets needed by the app; triggers a rolling restart
          flyctl secrets set \
            DISCORD_TOKEN="$DISCORD_TOKEN" \
#            DATABASE_URL="$DATABASE_URL" \
            ENVIRONMENT=production \
            PUBLIC_INVITE_URL="${INVITE_URL:-}" \
#            PROD_DATABASE_URL="PROD_DATABASE_URL" \
            -a matchmaker-prod-bot

  deploy:
    needs: prepare
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://matchmaker-prod-bot.fly.dev/health
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to Fly (production)
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl deploy --local-only -c fly.prod.toml
          flyctl apps restart matchmaker-prod-bot
