name: Deploy Staging

on:
  push:
    branches: [ staging ]
  workflow_dispatch: {}

concurrency:
  group: staging-deploy
  cancel-in-progress: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Set Fly secrets (staging)
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          DISCORD_TOKEN: ${{ secrets.STAGING_DISCORD_TOKEN }}
          DATABASE_URL: ${{ secrets.STAGING_DATABASE_URL }}
          INVITE_URL: ${{ secrets.STAGING_PUBLIC_INVITE_URL }}
        run: |
          # Set all secrets needed by the app; triggers a rolling restart
          flyctl secrets set \
            DISCORD_TOKEN="$DISCORD_TOKEN" \
            DATABASE_URL="$DATABASE_URL" \
            ENVIRONMENT=staging \
            PUBLIC_INVITE_URL="${INVITE_URL:-}" \
            -a matchmaker-staging-bot

  deploy:
    needs: prepare
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://matchmaker-staging-bot.fly.dev/health
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to Fly (staging)
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl deploy --local-only -c fly.staging.toml
          flyctl apps restart matchmaker-staging-bot
