name: Set Fly App Secrets (staging)
on:
  workflow_dispatch: {}
jobs:
  set-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Set secrets on app
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: |
          flyctl secrets set DISCORD_TOKEN="$DISCORD_TOKEN" ENVIRONMENT=staging -a matchmaker-staging-bot
