app = "matchmaker-staging-bot"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[processes]
  app = "python -m bot.main"

[http_service]
  internal_port = 8080
  processes = ["app"]         # add this line to tie to your process
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[http_service.checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"
    method = "GET"
    path = "/health"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
